### ISSUE TITLE
Checklist for adding new modules

### ISSUE THREAD

**Issue by natekupp** [dagster-io/dagster#1388]
Per @schrockn's comment in https://dagster.phacility.com/D207, we should have a checklist for adding new modules. off the top of my head, that's currently:

- [ ]  Create module directory with `setup.py`, `tox.ini`, `requirements.txt`, `README.md`
- [ ]  Update top-level `Makefile` for `install_dev_python_modules`
- [ ]  Update `.buildkite/pipeline.py`

Any others?

**Comment by natekupp** [comment]
See #1392 - we were missing some of these in `pipeline.py`

**Comment by natekupp** [comment]
With D217, `pipeline.py` does not need updating when new modules are created. Per #1396 we should do something for `publish.py`

**Comment by natekupp** [comment]
@alangenfeld FYI this issue also

**Comment by schrockn** [comment]
https://dagster.phacility.com/D310 add .coveragerc

**Comment by natekupp** [comment]
Closing, added a wiki page for this
