### ISSUE TITLE
[Tracking] Intermediate storage removal

### ISSUE THREAD

**Issue by yuhan** [dagster-io/dagster#4452]
Related issues:
- [ ] https://github.com/dagster-io/dagster/issues/4232 remove intermediate storage completely from documentation.
- [ ] https://github.com/dagster-io/dagster/issues/3368 we should restore this functionality back in IO managers.
- [ ] https://github.com/dagster-io/dagster/issues/4266 dagit config
